from setuptools import setup, find_packages

setup(
    name='InstanceSegFrac',
    packages=find_packages(include=["InstanceSegFrac", "InstanceSegFrac.*"]),
    version='0.2.1',
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.0.0",
        "acvl-utils>=0.2",
        "dynamic-network-architectures>=0.2",
        "tqdm",
        "dicom2nifti",
        "gdown",
        "nnunetv2",
        "scikit-image>=0.19.3",
        "MedPy",
        "scipy",
        "batchgenerators>=0.25",
        "numpy",
        "scikit-learn",
        "SimpleITK>=2.2.1",
        "pandas",
        "graphviz",
        "tifffile",
        "requests",
        "nibabel",
        "matplotlib",
        "seaborn",
        "imagecodecs",
        "yacs",
        "monai==1.4.0",
        "opencv-python",
    ],
)
